name: Deploy via SFTP
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.203.0.113.42 }}     # e.g. 203.0.113.42 (your VPS IP)
          username: ${{ secrets.root}}   # e.g. ubuntu
          ssh_private_key: ${{ secrets.@1Diomaster20 }} # your private key (add the public key to ~/.ssh/authorized_keys on the VPS)
          local_path: .
          remote_path: /var/www/html/phpform
          delete_remote_files: false